class ControllerError(Exception): ...

class ParseErorr(ControllerError): ...

class TopicIdIsEmpty(ParseErorr): ...

class InvalidRuTrackerLink(ParseErorr): ...

class InvalidMagnetLink(ParseErorr): ...
